# Generated by Django 3.1.1 on 2020-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cool',
            name='embed_code',
            field=models.TextField(default=1, verbose_name='enbade'),
            preserve_default=False,
        ),
    ]
